server:
  port: 8010
  servlet:
    session:
      cookie:
        same-site: Lax


spring:
  application:
    name: login-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: agelessbaby89@gmail.com
    password: euqqyzlxdrugvpne
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: 101.42.116.10
      password: Root123456@

  datasource:
    url: jdbc:mysql://101.42.116.10:3306/clinic_booking?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Root123456@
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.iss.auth.entity

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: Root123456@
