server:
  port: 8082  

spring:
  application:
    name: queue-service
  cloud:
    nacos:
      discovery:
        server-addr: 34.122.104.53:8848

  datasource:
    url: jdbc:mysql://101.42.116.10:3306/clinic_booking?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Root123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
