server:
  port: 8088  # Gateway ????

spring:
  application:
    name: gateway  # ??????

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos ??????

    gateway:
      routes:
        - id: clinic_route
          uri: lb://clinic-service  # ? ?? Nacos ?????????
          predicates:
            - Path=/clinic/**       # ???? /clinic ?????
        - id: login_route
          uri: lb://login-service  # ? ?? Nacos ?????????
          predicates:
            - Path=/login/**       # ???? /clinic ?????