server:
  port: 8088  # 设置服务端口

spring:
  session:
    store-type: redis  # 使用 Redis 存储 Session

  cookie:
    name: SESSIONID    # 设置 Cookie 名称
    http-only: true     # 禁止客户端访问 Cookie
    secure: false       # 如果使用 HTTPS，设置为 true
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  gateway:
    routes:
      - id: clinic_route
        uri: lb://clinic-service
        predicates:
          - Path=/api/clinic/**
        filters:
          - JwtSessionAuthenticationFilter  # 使用自定义的 JWT 校验过滤器

      - id: login_route
        uri: lb://login-service
        predicates:
          - Path=/api/auth/**
        filters:
          - JwtSessionAuthenticationFilter  # 使用自定义的 JWT 校验过滤器
