server:
  port: 8088

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 35.247.152.162:8848
        username: nacos
        password: Root123456@

    gateway:
      routes:
        - id: clinic_route
          uri: lb://clinic-service
          predicates:
            - Path=/api/clinic/**

        - id: login_route
          uri: lb://login-service
          predicates:
            - Path=/api/auth/**

        - id: queue_route
          uri: lb://queue-service
          predicates:
            - Path=/api/queue/**

        - id: patient_medicine_route
          uri: lb://patient-medicine-service
          predicates:
            - Path=/api/patient_medicine/**

