server:
  port: 8084

spring:
  application:
    name: patient-medicine-service
  cloud:
    nacos:
      discovery:
        server-addr: 35.247.152.162:8848
        username: nacos
        password: Root123456@
