server:
  port: 8084

spring:
  application:
    name: patient-medicine-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848


management:
  server:
    port: 8091
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
