name: CI clinic-service

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'gateway/**'
      - '.github/workflows/clinic_service_ci.yaml'
      - 'common/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'gateway/**'
      - '.github/workflows/clinic_service_ci.yaml'
      - 'common/**'

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.export-tag.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Shutdown system MySQL service (if running)
        run: sudo service mysql stop

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -pl clinic-service -am clean install

      - name: Build Docker Image
        run: |
          REPO=${{ secrets.GCP_ARTIFACT_REPO }}
          TAG=${{ github.sha }}
          docker build -t $REPO/clinic-service:$TAG -f clinic-service/Dockerfile clinic-service/

      - name: Save Docker Image to TAR
        run: |
          REPO=${{ secrets.GCP_ARTIFACT_REPO }}
          TAG=${{ github.sha }}
          docker save $REPO/clinic-service:$TAG -o clinic-service.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clinic-service-image
          path: clinic-service.tar

      - name: Export Tag for Push Job
        id: export-tag
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: clinic-service-image
          path: .

      - name: Load Docker Image
        run: docker load -i clinic-service.tar

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCP
        run: |
          REGION=$(echo "${{ secrets.GCP_ARTIFACT_REPO }}" | cut -d/ -f1)
          gcloud auth configure-docker $REGION

      - name: Push Docker Image to GCP
        run: |
          REPO=${{ secrets.GCP_ARTIFACT_REPO }}
          TAG=${{ needs.build.outputs.tag }}
          docker push $REPO/clinic-service:$TAG
          docker tag $REPO/clinic-service:$TAG $REPO/clinic-service:latest
          docker push $REPO/clinic-service:latest
